### ISSUE TITLE
Merge Sphero robot types into one tab

### ISSUE THREAD

**Issue by fstanis** [google/coding-with-chrome#145]
Right now we support:

- Sphero 2.0
- Sphero SPRK+
- Sphero BB-8

My understanding is that all 3 are (reasonably) similar, so it perhaps makes more sense to merge all 3 into one tab called "Sphero" and add a dropdown to the editor where the user will be able to select a Sphero variant they are using.

Main reason is that right now adding a new language like Python will mean having 6 different Sphero tabs (Python x 3 Sphero variants and JS x 3 Sphero variants) which is not ideal.

Thoughts?

**Comment by MarkusBordihn** [comment]
Unfortunately even if the robots using an similar control protocol each robot is different in the available actions and the behavior.

For example the BB-8 is keeping moving forward and the Sphero SPRK+ is stopping automatically.
The Sphero 2.0 using Bluetooth 2.0 so it needs to be separated in case of pre-loading and preparation.

The Python part should be just an additional editor overlayer which could be turned on.
If this overlay is turned on instead of the JavaScript code the Python code is send to the Sandbox and the sandbox is handling the Python code instead of JavaScript.

So the Python support should not be done as additional module, it should be added as additional Editor layer so that it could be used with every module.
