### ISSUE TITLE
Video Resources

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#44]
Need some location of video resources. Very important to have them next to the main interface, but would also put them in the 'built in gallery' you have created. Perhaps consider a 'group of videos' 

Suggest opening main UI and starting the video in separate window.

**Comment by ergelo** [comment]
I'm currently implementing a 'Video Tutorial' button in the relevant programming language interface. Once one clicks on that, they will see all the videos for that language. Ideally, I would like to do the same for code examples, so to keep them organised and not cluttering the interface too much. 

At a broader level, I'd like to create a 'resources' or 'tutorials' area, maybe accessible from the sandwich menu, that includes all examples and all videos, perhaps divided by language or genre or whatever. @MarkusBordihn does this sound like a good overall (initial) plan?


That being said, both @MartenvanWezel and I agree that the extra level of depth, as well as the clutter, isn't great. One thought I had is to have an extra drawer, perhaps on the right, that contains available resources for the language one is currently viewing. Or we could have a different, more tabular, view for resources, so that we could include both videos and examples in one screen. There are many options. 

I propose that as we currently only have a handful of videos, I'll just stick to what I'm currently implementing - and we can discuss a broader solution to this problem for when we'll have more material.
