### ISSUE TITLE
Showing line numbers for run time errors.

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#93]
for example:
1/ advanced > programming > javascript > circle animation
2/ create a typo somewhere
3/ would be nice to see a line number of the error?

Somehow I thought we already had this feature, but it leaves me in the dark WHERE the error is.

<img width="1281" alt="screen shot 2016-11-24 at 9 25 23 pm" src="https://cloud.githubusercontent.com/assets/16690260/20610077/9b6c6ea8-b28c-11e6-9f8d-d7ebf223badb.png">

(the fact that the line with the error highlighted is just my highlighting, the editor itself doesn't show it)

**Comment by MarkusBordihn** [comment]
In general there is an different between syntax error and runtime errors.
For the runtime errors we don't have any line numbers, because the executed code is not 1:1 the same as the visible code.

If you copy the same line outside of the function it will become an syntax error which will be detected by this function.

**Comment by MartenvanWezel** [comment]
I see - that does make sense from a 'code structure' level, but it would be nice in some way to do this inside functions that can only be interpreted at runtime too. You mentioned we might be able to implement this at heavy processing cost (so it should be enabled optionally?) but it would be a cool one so let's leave this as a feature request?
